/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exam;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void firstLower() {
        assertEquals(1, Math.min(1, 2));
    }
}
